### ISSUE TITLE
How to output codeclimate report for Gitlab

### ISSUE THREAD

**Issue by stefanoco** [tomasbjerre/violation-comments-to-gitlab-command-line#1]
I noticed this repo while looking for a better integration of static analysis tools with our dev flow based on Gitlab. While this sounds interesting it's not very clear to me (and maybe to many others) how to use it. Does it fit the "Implementing a custom tool" part [mentioned here](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#configuring-jobs-using-variables)?

**Comment by tomasbjerre** [comment]
You can output codeclimate json with this tool: https://github.com/tomasbjerre/violations-command-line
