### ISSUE TITLE
Unicode symbols in comment display escaped

### ISSUE THREAD

**Issue by mak-42** [tomasbjerre/violation-comments-to-gitlab-command-line#11]
It parses checkstyle error report and publish comment like that (all Unicode symbols in the text of warning are escaped):
![image](https://github.com/tomasbjerre/violation-comments-to-gitlab-command-line/assets/17267223/233a8aab-a31f-4a1f-9a6f-1518cbfd28f5)

The source checkstyle report looks like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.37">
..<removed>..
<file name="<removed>\DictionaryConfig.java">
<error line="12" severity="warning" message="Первое предложение Javadoc комментария не закончено (нет точки) или отсутствует." source="com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck"/>
</file>
..<removed>..
</checkstyle>
```

I enabled debug info but it contained nothing useful (no request body). :(

It seems the problem is in the transformation to GitLab comment. The transformation into Code Climate Report (by "violations-command-line")  goes fine. Unicode symbols copied into it without transformation.

**Comment by tomasbjerre** [comment]
Not sure if it helps to supply custom template with the `-comment-template` parameter.

And use tripple brackets, `{{{violation.message}}}` as example in readme here: https://github.com/tomasbjerre/violation-comments-lib

**Comment by mak-42** [comment]
Thanks a lot. It solved my problem.
