### ISSUE TITLE
Changing MR to WIP creates unexpected results

### ISSUE THREAD

**Issue by riomus** [tomasbjerre/violation-comments-to-gitlab-command-line#4]
When using feature that changes MR titles to WIP, I get unexpected results. If  I have MR that is already in WIP state, the tool prepends 'WIP: (VIOLATIONS)' to the title. Resulting in a prefix "WIP: (VIOLATIONS) WIP:" in the title. I think that expected behaviour would be to detect existing WIP and result in "WIP: (VIOLATIONS)" prefix.

**Comment by tomasbjerre** [comment]
Fixed in 1.15.0!
